- .gitignore
- glidertest/fetchers.py
- notebooks/demo.ipynb
- pyproject.toml
- requirements-dev.txt
- requirements.txt
This PR achieves several steps collected in #1 namely:
> Add core files

- requirements.txt
Chiara is showing me how to do this.
> Update requirements.txt - add numpy

- glidertest/tools.py
Not sure this is the best way to do it but I just put it here so we have something to start with. There is the demo with the functions being used in the notebook folder
> Created a tool.py to have functions

- requirements.txt
Resolves #34 
This should be addressed upstream in skyfield itself
> fix sgp4 for skyfield

- notebooks/demo.ipynb
Testing how to do a pull request.
> Spelling correction

- .github/dependabot.yml
This bot checks the CI config to make sure everything stays up to date
> [CI] add dependabot

- notebooks/demo.ipynb
This will make the documentation a little prettier
> [DOCS] ignore warnings in notebook

- glidertest/tools.py
- notebooks/demo.ipynb
- tests/test_tools.py
This sets hopefully sensible default dates and date ranges for all functions that need them
> [FEAT] set default dates for all functions

- glidertest/tools.py
There is the function to remove errors at the beginning of the demo notebook but this was if the functions are used individually, the error should not raise
> Chiara patch 24

- tests/test_tools.py
Uses code stolen from https://github.com/callumrollo/glidertest/pull/80
> [FEAT] Add tests for all functions 

- glidertest/tools.py
- requirements-dev.txt
- requirements.txt
Want to clear these out before making the conda-forge recipe
> [DEP] remove unused dependencies

- glidertest/plots.py
- notebooks/demo.ipynb
Fixing some plot issues introduced in the standardization of plots
> [BUG] Fix plots

- notebooks/demo.ipynb
This addresses issue #127, reordering the demo notebook by 
- Load dataset
- Generate overview
Then sections divided by sensors (or computed values) in the order:
- CTD
- Dissolved oxygen
- Bio-optics 
- PAR
- Vertical velocity
> [REFACTOR] Change order of demo.ipynb

- glidertest/plots.py
Eleanor wanted the T/S to look like this with the histograms on the two axis
> [FIX] Adjusted T/S plot with histograms on the two sides

- glidertest/plots.py
- notebooks/demo.ipynb
- tests/test_plots.py
Thank you for your comments Callum, that's really helpful. 
I'll make sure to work on a different branch.
I've just updated the code accordingly.
> Add sampling period

- CONTRIBUTING.md
Update all the links now that we have migrated to OceanGliders
> [FIX] Update CONTRIBUTING.md after migration

- docs/source/index.rst
Update the link for new issues now that we migrated to OceanGliders
> [FIX] Update docs after migration

- glidertest/plots.py
This way we can better visualize if there is quenching or not (chla range can be big and then we cannot see much)
> [FIX] Use log scale for chla plot for quenching assess

- glidertest/plots.py
We need to have ax as a variable so we can insert easily the figure in other figures
> [FIX] Add ax to basic variable plot

- tests/test_plots.py
This is just in case we change the labels in the utilities functions, then we do not get into troubles with the tests and do not have to change it here too
> [FIX] Adjusted labels check with the use of utilities functions

- glidertest/fetchers.py
- tests/test_plots.py
I have reprocessed the VOTO seaexplorer OG1-ish demo dataset with several improvements:
- correct naming of PROFILE_NUMBER
- remove legacy VOTO attributes
- passes the current (incomplete) cc-plugin https://github.com/uw-farlab/cc-plugin-og
> improved demo dataset

- glidertest/plots.py
- glidertest/utilities.py
Looking like this atm. Happy to change the label and unit as I am not sure it is the best way to write it. Maybe it is ok to leave the density label as we had before
> [FEAT] Plot sigma-T instead of density in basic_vars plot

- glidertest/utilities.py
- requirements-dev.txt
Also edited a python file so that the workflow will trigger
> Pin sphinx to fix docs

- glidertest/tools.py
- glidertest/utilities.py
- requirements-dev.txt
- requirements.txt
- tests/test_tools.py
- tests/test_utilities.py
Implementation of GT MLD. I had to change certain parts to make it OG1 compliant.
Apart from the actual variable names, I also changed this part so it could recognize up and down cast
`ln 60        direction = 1 if np.unique(df.index % 1 == 0) else -1`
The index I get is just the profile number so I would never get -1. Instead, I did this 
`direction = 1 if np.nanmean(np.diff(df.DEPTH))> 0 else -1`
> [FEAT] Implement glidertools MLD computation

- glidertest/summary_sheet.py
- tests/test_mission_summary.py
> [FEAT] Add summary sheet template

- glidertest/summary_sheet.py
- tests/test_mission_summary.py
Added hysteresis check with both range and mean in the summary table 
[sea045_Unknown_report20250416.pdf](https://github.com/user-attachments/files/19772663/sea045_Unknown_report20250416.pdf)
> [FEAT] Added hysteresys check with range too
